#!/bin/sh
#########################################################################
# File Name: makemvn
# Author: Carson Wang
# mail: carson.wang@droi.com
# Created Time: 2017-03-14 11:27:56
#########################################################################

project_name='infohub'

packaging='jar'

old='1.2.22'
new='1.2.23'
dir='com/idroi/infohub'
meta_file='maven-metadata.xml'
now=$(date +'%Y%m%d%H%M%S')

old_dir="$dir/$old"
new_dir="$dir/$new"

parent_dir="$PWD"

version='0.0.1'
intro="MakeMaven Command Line Interface
Version:$version written by Carson Wang

Gerenal Usage:
  \033[32;1mmakemvn [command] [<args>]\033[m

  \033[34;1m[--help] [--version] [--init] [--run]\033[m

Abbreviated comparison:

  \033[34;1m[-h] [-v] [-i] [-r]\033[m

These are common Makemvn commands used in various situations.

Available Commands:
  version     Print version number of Makemvn
  init        Initialize maven project
  run         Deploy maven's template

See 'makemvn [command] --help' or 'makemvn [command] -h' to read about a specific subcommand excluding [--help] [--version]."

intro_init="Initialize maven project

Usage:
  mmakemvn --init \$groupid \$artifactid
  makemvn init \$groupid \$artifactid
  makemvn -i \$groupid \$artifactid
  makemvn --init
  makemvn init
  makemvn -i

Define argument:
  groupid       It will identify project uniquely across all projects. eg. \033[35;1m'org.apache.maven'\033[m, \033[35;1m'org.apache.commons'\033[m
  artifactid    It's the name of the jar without version. eg. \033[35;1m'maven'\033[m, \033[35;1m'commons-math'\033[m

  See more on maven official webpage: https://maven.apache.org/guides/mini/guide-naming-conventions.html"


#-- check OS to determine sed's mode
if [ "$(uname)" == "Darwin" ]; then
    #echo "Do something under Mac OS X platform"
    sed_mode="-ie"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    #echo "Do something under GNU/Linux platform"
    sed_mode="-i"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    echo "Do something under 32 bits Windows NT platform"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    echo "Do something under 64 bits Windows NT platform"
fi


suggestion(){
    command="$1"
    command="${command//[!a-zA-Z]/}"
    if [[ "$command" == "h"* ]]; then
        echo "Did you mean this?"
        echo "\thelp"
    elif [[ "$command" == "v"* ]]; then
        echo "Did you mean this?"
        echo "\tversion"
    elif [[ "$command" == "i"* ]]; then
        echo "Did you mean this?"
        echo "\tinit"
    elif [[ "$command" == "r"* ]]; then
        echo "Did you mean this?"
        echo "\trun"
    elif [[ "$command" == "p"* ]]; then
        echo "Did you mean this?"
        echo "\tpush"
    fi
}


init(){
   echo "\033[31;1mInitialization failed.\033[m"
   echo "Two arguments, which are groupid and artifactid, are required."
   echo "Use 'makemvn init --help' or 'makemvn -i --help' to see more."
   echo "Do you want to continue running 'makemvn init' command [y/n]?"
   echo "If yes, it will lead you to execute; otherwise, the program will terminate."
   while true; do
       read yn
       case $yn in
           [Yy]* )
               echo "Please enter your groupID, such as, 'com.idroi' or 'com idroi'."
               read groupIdArry
               echo "Please enter your artifactId, such as, 'infohub'."
               read artifactId
               break;;
           [Nn]* ) exit;;
           * ) echo "\033[31;1mInput error. Please answer yes or no.\033[m";;
       esac
   done

}

init_run(){
    while true; do
        read -p "Please enter your packaging type (jar or aar): " packaging
        case $packaging in
            jar* ) packaging="jar"; break;;
            aar* ) packaging="aar"; break;;
            * ) echo "\033[31;1mInput error. Please answer jar or aar.\033[m";;
        esac
    done

    mkdir -p ".makemvn"
    cd ".makemvn"
    project_data="{\"groupId\":$1, \"artifactId\":$2, \"packaging\":$packaging, \"version:0.0.1\"}"
    echo "$project_data" > "makemvn.project"
    cd ..

    array=(${1//./ })
    for i in "${!array[@]}"; do
        mkdir -p "${array[i]}"
        cd "${array[i]}"
    done
    mkdir -p "$2"
    cd "$2"

    meta_data="<metadata>
  <groupId>$1</groupId>
  <artifactId>$2</artifactId>
  <versioning>
    <release>0.0.1</release>
    <versions>
      <version>0.0.1</version>
    </versions>
    <lastUpdated>$now</lastUpdated>
  </versioning>
</metadata>"
    echo "$meta_data" > $meta_file

    mkdir -p "0.0.1"
    cd "0.0.1"
    pom_data="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<project xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\" xmlns=\"http://maven.apache.org/POM/4.0.0\"
    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">
  <modelVersion>4.0.0</modelVersion>
  <groupId>$1</groupId>
  <artifactId>$2</artifactId>
  <version>0.0.1</version>
  <packaging>$packaging</packaging>
  <description>POM was created from install:install-file</description>
</project>"
    echo "$pom_data" > "$2-0.0.1.pom"

    cd $parent_dir
}



#-- check command argument
if [ -z "$1" ]; then
    echo "\033[31;1mCommand argument is required.\033[m"
    echo "Use 'makemvn --help' or 'makemvn -h' for more information about command."
    exit 1
elif [ "$1" == "-h" -o "$1" == "--help" -o "$1" == "help" ]; then
    echo "$intro"
    exit 0
elif [ "$1" == "-v" -o "$1" == "--version" -o "$1" == "version" ]; then
    echo "Makemvn version $version"
    exit 0
elif [ "$1" == "-i" -o "$1" == "--init" -o "$1" == "init" ]; then
    if [ "$2" == "-h" -o "$2" == "--help" -o "$2" == "help" ]; then
        echo "$intro_init"
    elif [ -n "$2" -a -n "$3" ]; then
        echo "Initializing maven project..."
        init_run "$2" "$3"
    else
        echo "Initializing maven project..."
        init
        groupId=($groupIdArry)
        groupId="$( IFS=$'.'; echo "${groupId[*]}" )"
        init_run $groupId $artifactId
    fi
    exit 0
elif [ "$1" == "-r" -o "$1" == "--run" -o "$1" == "run" ]; then
    echo "Deploying maven's template..."
    if [ "$2" == "-h" -o "$2" == "--help" -o "$2" == "help" ]; then
        echo "help"
    elif [ -n "$2" ]; then
        if [ -f ./.makemvn/makemvn.project ]; then
            if [ -f "$2" ]; then
                echo "Please enter your new version, such as, '0.0.1'"
                read project_version
                if [[ $project_version =~ ^[0-9]*.[0-9]*.[0-9]*$ ]]; then
                    echo "YES"
                    tes=($project_version)
                    tes="$( IFS=$'.'; echo "${tes[*]}" )"
                    echo "$tes"
                else
                    echo "NO"
                    echo "$project_version"
                fi
            fi
        else
            echo "\033[31;1mDeployment error.\033[m"
            echo "Can't find working directory: $PWD/.makemvn"
            echo "Please take 'makemvn init \$groupId \$artifactId' to initialize first."
            echo "Use 'makemvn init --help' or 'makemvn -i --help' to see more."
        fi
    else
        echo "Failed"
    fi
    exit 0
else
    echo "\033[31;1mUnknown command '$1' for 'makemvn'.\033[m"
    echo "Use 'makemvn --help' to see more."
    suggestion "$1"
    exit -1
fi


#-- create directory for new version
mkdir -p $new_dir
cp -r $old_dir/* $new_dir
mv $new_dir/$project_name-$old.pom $new_dir/$project_name-$new.pom


#-- revise aar and pom
sed $sed_mode "s/$old/$new/g" $new_dir/$project_name-$new.pom
rm $new_dir/$project_name-$old.aar
cp $project_name-release.aar $new_dir/$project_name-$new.aar


#-- change directory to revise maven-metadata and last updated
cd $dir
sed $sed_mode "/<release>/c\ \ \ \ <release>$new<\/release>" $meta
sed $sed_mode "/<version>$old<\/version>/a \ \ \ \ \ \ <version>$new<\/version>" $meta

sed $sed_mode "/<lastUpdated>/c\ \ \ \ <lastUpdated>$now<\/lastUpdated>" $meta


#-- delete backup files (name: ***e) when OS is Mac
if [ "$sed_mode" == "-ie" ]; then
    rm "$meta"e
    rm $new/$project_name-$new.pome
fi

cd -
